-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgn+XGnl2A4HpqywG1
0e2hDSuPppFVtMLWNnv4DVb4zU+gCgYIKoZIzj0DAQehRANCAASyMChV/jSKvCbg
TDJDuutGrPvibR8oKUCeTJP6vYqV22GbjfXNRaB40lidi50GH5CoxEchQO00X2ma
XDyWqAGK
-----END PRIVATE KEY-----